site_name: Bt's Docs >_
site_url: https://doc.ccc2.icu
site_author: bt
copyright: <a href="https://beian.miit.gov.cn/" target="blank">皖ICP备20006403号-1</a>
theme:
    name: 'material'
    language: zh
    logo: logo.svg
    favicon : logo.svg
    palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/brightness-4
        name: 切换黑夜模式 

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: light green
      toggle:
        icon: material/brightness-7
        name: 切换白天模式
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.tracking
        - navigation.tabs
        - navigation.path
        - navigation.top
        - navigation.footer
# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.highlight: # 代码块高亮
    anchor_linenums: true
    linenums: true # 显示行号
    auto_title: true # 显示编程语言名称
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 


extra:
  social:
    - icon: simple/wechat
      link: "#"
      name: btonf0302
    - icon: material/email
      link: mailto:<btonf@outlook.com>
      