site_name: Bt's Docs >_
site_url: https://doc.ccc2.icu
site_author: bt
copyright: <a href="https://beian.miit.gov.cn/" target="blank">皖ICP备20006403号-1</a> © 2024 - 2025 CCC2
repo_url: https://github.com/btONF/btonf.github.io #存储库URL
repo_name: btONF/btonf.github.io
theme:
    name: 'material'
    language: zh
    logo: logo.svg
    favicon : logo.svg
    font:
      text: Noto Sans SC
      code: Roboto Mono
    icon:
      repo: fontawesome/brands/git-alt
    palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: 黑夜模式 

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: 白天模式
    features:
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.tracking
        - navigation.tabs
        - navigation.path
        - navigation.top
        - navigation.footer
        - navigation.expand     
        - content.code.copy
        - content.code.select
        - content.code.annotate
        
# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - roamlinks


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
  - javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js

extra_css:
  - stylesheets/extra.css
  
extra:
  social:
    - icon: simple/wechat
      link: "#"
      name: btonf0302
    - icon: material/email
      link: mailto:<btonf@outlook.com>
      